#!/bin/bash

# setup monitors
xrandr --output HDMI-O --primary --mode 1920x1080 --output DP-5 --mode 1920x1080 --left-of HDMI-0

# kill any currently running processes
pkill ckb-next &
pkill polybar &
pkill pipewire &
pkill Discord &
pkill spotify &

# pause to let processes be killed
sleep 1

# start apps in background
picom -b --config ~/.config/picom.conf &
pipewire &
ckb-next -b &
polybar main -r &
polybar secondary -r &

# start main gui applications
/usr/share/discord/Discord &
flatpak run com.spotify.Client &
firefox --new-window "file:///home/violet/Projects/violetonline.org/landing-page/index.html" &
